# Generated by Django 2.0.2 on 2018-02-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180211_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='value',
        ),
    ]
