# Generated by Django 2.0.2 on 2018-02-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_option_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.IntegerField(verbose_name='MaxValue')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Question', verbose_name='所属数量问题')),
            ],
            options={
                'verbose_name_plural': 'maxvalue',
            },
        ),
    ]
