# Generated by Django 2.0.2 on 2018-02-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_maxvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='vendor_view',
            field=models.BooleanField(default=False),
        ),
    ]
